### PR TITLE
replace testing to run against staging

### PR DESCRIPTION
**Pull request by schehata**

### CODE REVIEW

**Review by lukasmalkmus — DISMISSED** [review]
LGTM

**Comment by lukasmalkmus** [comment]
Unless @bahlo wants them to run against dev and staging?

**Comment by bahlo** [comment]
both pls ❤️

**Comment by lukasmalkmus** [comment]
And one final thing: I found a new pattern I personally prefer, figure out for yourself if you want to use that: https://github.com/axiomhq/axiom-go/pull/229.

**Review by bahlo — APPROVED** [review]
let's gooo

**Pull request merged**
